pub mod _02_guessing_game;
mod _03_functions_and_variables;
mod _04_ownership;
mod _05_structs;
mod _06_enums;
mod _08_collections;
mod _09_errors;
mod _10_generic_types;
mod _10_traits;
mod _10_lifetimes;
mod _11_tests;
mod _13_closures;
mod _13_iterators;
pub mod _14_doctest;
mod _15_box;
mod _15_deref_and_drop;
mod _15_rc_smart_pointer;
mod _15_refcell_smart_pointer;
mod _15_weak_smart_pointer;
mod _15_mocks;
